@local @javascript @local_elisreports @uccr_compare
Feature: User Class Completion/Details reports compare generation base.

    Background:
        Given I log in as "admin"
        And the following ELIS users exist:
          | username | idnumber | firstname | lastname |
          | testelis9010a | testelis9010a | Test | Elis9010a |
          | testelis9010b | testelis9010b | Test | Elis9010b |
          | testelis9010c | testelis9010c | Test | Elis9010c |
          | testelis9010d | testelis9010d | Test | Elis9010d |
        And the following ELIS usersets exist:
          | name | parent_name |
          | US-9010A | top |
        And the following ELIS userset enrolments exist:
          | user_idnumber | userset_name | plugin |
          | testelis9010a | US-9010A | manual |
          | testelis9010b | US-9010A | manual |
        And the following ELIS courses exist:
          | name | idnumber | credits | completion_grade |
          | CD-NonProg1 Name| CD-NonProg1 | 2.14 | 55 |
          | CD-9010A1 Name | CD-9010A1 | 1.25 | 51 |
          | CD-9010A2 Name | CD-9010A2 | 2.75 | 52 |
          | CD-9010A3 Name | CD-9010A3 | 3.15 | 53 |
          | CD-9010B1 Name | CD-9010B1 | 1.15 | 51 |
          | CD-9010B2 Name | CD-9010B2 | 2.25 | 52 |
          | CD-9010B3 Name | CD-9010B3 | 3.85 | 53 |
        And the following ELIS classes exist:
          | idnumber | course_idnumber |
          | CI-NonProg101 | CD-NonProg1 |
          | CI-9010A1-101 | CD-9010A1 |
          | CI-9010A1-102 | CD-9010A1 |
          | CI-9010A1-103 | CD-9010A1 |
          | CI-9010A2-201 | CD-9010A2 |
          | CI-9010A2-202 | CD-9010A2 |
          | CI-9010A2-203 | CD-9010A2 |
          | CI-9010A3-301 | CD-9010A3 |
          | CI-9010A3-302 | CD-9010A3 |
          | CI-9010A3-303 | CD-9010A3 |
          | CI-9010B1-101 | CD-9010B1 |
          | CI-9010B2-202 | CD-9010B2 |
          | CI-9010B3-303 | CD-9010B3 |
        And the following ELIS programs exist:
          | idnumber | name | reqcredits |
          | PRG-9010A | PRG-9010A Name | 7.15 |
          | PRG-9010B | PRG-9010B Name | 7.25 |
        And the following ELIS program enrolments exist:
          | user_idnumber | program_idnumber |
          | testelis9010a | PRG-9010A |
          | testelis9010a | PRG-9010B |
          | testelis9010b | PRG-9010B |
        And the following ELIS program course assignments exist:
          | course_idnumber | program_idnumber | required |
          | CD-9010A1 | PRG-9010A | 1 |
          | CD-9010A2 | PRG-9010A | 1 |
          | CD-9010A3 | PRG-9010A | 1 |
          | CD-9010B1 | PRG-9010B | 1 |
          | CD-9010B2 | PRG-9010B | 1 |
          | CD-9010B3 | PRG-9010B | 1 |
        And the following ELIS class enrolments exist:
          | user_idnumber | class_idnumber | completestatus | grade | credits | locked |
          | testelis9010a | CI-NonProg101 | passed | 66.77 | 2.14 | 1 |
          | testelis9010b | CI-NonProg101 | failed | 27.89 | 0.15 | 1 |
          | testelis9010c | CI-NonProg101 | notcompleted | 0 | 0.1 | 0 |
          | testelis9010a | CI-9010A1-101 | failed | 10.45 | 0.1 | 1 |
          | testelis9010a | CI-9010A1-102 | failed | 40.65 | 0.25 | 1 |
          | testelis9010a | CI-9010A1-103 | notcompleted | 0 | 0 | 0 |
          | testelis9010a | CI-9010A2-201 | failed | 15.45 | 0.1 | 1 |
          | testelis9010a | CI-9010A2-202 | passed | 60.65 | 2.65 | 1 |
          | testelis9010a | CI-9010A2-203 | notcompleted | 0 | 0 | 0 |
          | testelis9010a | CI-9010A3-301 | failed | 5.45 | 0.25 | 1 |
          | testelis9010a | CI-9010A3-302 | passed | 54.65 | 2.9 | 1 |
          | testelis9010a | CI-9010A3-303 | notcompleted | 0 | 0.1 | 0 |
          | testelis9010a | CI-9010B1-101 | passed | 76.58 | 1.15 | 1 |
          | testelis9010b | CI-9010B1-101 | failed | 45.67 | 0.15 | 1 |
          | testelis9010a | CI-9010B2-202 | notcompleted | 0 | 0 | 0 |
          | testelis9010b | CI-9010B2-202 | passed | 57.89 | 2.25 | 1 |
          | testelis9010a | CI-9010B3-303 | failed | 15.67 | 0 | 1 |
          | testelis9010b | CI-9010B3-303 | notcompleted | 0 | 0.1 | 0 |


    Scenario:
        Then I visit all details reports of the following UCC report URLs:
          | reporturl |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=&filter-autoc_textentry=&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=&filter-autoc_textentry=&filter-uid_dropdown={local_elisprogram_uset}+1&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=&filter-autoc_textentry=&filter-ccc-curriculum-name=&filter-uid_dropdown=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=&filter-autoc_textentry=&filter-ccc-curriculum-name={local_elisprogram_pgm}+1&filter-uid_dropdown=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=&filter-autoc_textentry=&filter-ccc-curriculum-name={local_elisprogram_pgm}+2&filter-uid_dropdown=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=&filter-autoc_textentry=&filter-ccc-courseset-name=&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=&filter-autoc_textentry=&filter-ccc-course-name=&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=&filter-autoc_textentry=&filter-ccc-course-name={local_elisprogram_crs}+2&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=&filter-autoc_textentry=&filter-ccc-course-name={local_elisprogram_crs}+3&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=&filter-autoc_textentry=&filter-ccc-course-name={local_elisprogram_crs}+6&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=&filter-autoc_textentry=&filter-ccc-course-name={local_elisprogram_crs}+7&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=&filter-autoc_textentry=&filter-ccc-class-idnumber=&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=&filter-autoc_textentry=&filter-ccc-class-idnumber={local_elisprogram_cls}+1&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=&filter-autoc_textentry=&filter-ccc-class-idnumber={local_elisprogram_cls}+2&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=&filter-autoc_textentry=&filter-ccc-class-idnumber={local_elisprogram_cls}+11&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=&filter-autoc_textentry=&filter-ccc-class-idnumber={local_elisprogram_cls}+12&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=&filter-autoc_textentry=&filter-completionstatus=&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=&filter-autoc_textentry=&filter-completionstatus=0&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=&filter-autoc_textentry=&filter-completionstatus=1&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=&filter-autoc_textentry=&filter-completionstatus=2&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=&filter-autoc_textentry=&filter-completionstatus=9999&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=&filter-autoc_textentry=&filter-summarycolumns:user_email=0&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=&filter-autoc_textentry=&filter-summarycolumns:user_email=1&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=&filter-autoc_textentry=&filter-summarycolumns:cur_name=0&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=&filter-autoc_textentry=&filter-summarycolumns:cur_name=1&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=&filter-autoc_textentry=&filter-summarycolumns:cur_timecompleted=0&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=&filter-autoc_textentry=&filter-summarycolumns:cur_timecompleted=1&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=&filter-autoc_textentry=&filter-summarycolumns:cur_certificate=0&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=&filter-autoc_textentry=&filter-summarycolumns:cur_certificate=1&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=&filter-autoc_textentry=&filter-detailcolumns:cur_name=0&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=&filter-autoc_textentry=&filter-detailcolumns:cur_name=1&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=&filter-autoc_textentry=&filter-detailcolumns:class_role=0&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=&filter-autoc_textentry=&filter-detailcolumns:class_role=1&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010a&filter-autoc_textentry=Test%20Elis9010a&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010a&filter-autoc_textentry=Test%20Elis9010a&filter-uid_dropdown={local_elisprogram_uset}+1&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010a&filter-autoc_textentry=Test%20Elis9010a&filter-ccc-curriculum-name=&filter-uid_dropdown=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010a&filter-autoc_textentry=Test%20Elis9010a&filter-ccc-curriculum-name={local_elisprogram_pgm}+1&filter-uid_dropdown=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010a&filter-autoc_textentry=Test%20Elis9010a&filter-ccc-curriculum-name={local_elisprogram_pgm}+2&filter-uid_dropdown=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010a&filter-autoc_textentry=Test%20Elis9010a&filter-ccc-courseset-name=&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010a&filter-autoc_textentry=Test%20Elis9010a&filter-ccc-course-name=&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010a&filter-autoc_textentry=Test%20Elis9010a&filter-ccc-course-name={local_elisprogram_crs}+2&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010a&filter-autoc_textentry=Test%20Elis9010a&filter-ccc-course-name={local_elisprogram_crs}+3&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010a&filter-autoc_textentry=Test%20Elis9010a&filter-ccc-course-name={local_elisprogram_crs}+6&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010a&filter-autoc_textentry=Test%20Elis9010a&filter-ccc-course-name={local_elisprogram_crs}+7&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010a&filter-autoc_textentry=Test%20Elis9010a&filter-ccc-class-idnumber=&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010a&filter-autoc_textentry=Test%20Elis9010a&filter-ccc-class-idnumber={local_elisprogram_cls}+1&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010a&filter-autoc_textentry=Test%20Elis9010a&filter-ccc-class-idnumber={local_elisprogram_cls}+2&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010a&filter-autoc_textentry=Test%20Elis9010a&filter-ccc-class-idnumber={local_elisprogram_cls}+11&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010a&filter-autoc_textentry=Test%20Elis9010a&filter-ccc-class-idnumber={local_elisprogram_cls}+12&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010a&filter-autoc_textentry=Test%20Elis9010a&filter-completionstatus=&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010a&filter-autoc_textentry=Test%20Elis9010a&filter-completionstatus=0&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010a&filter-autoc_textentry=Test%20Elis9010a&filter-completionstatus=1&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010a&filter-autoc_textentry=Test%20Elis9010a&filter-completionstatus=2&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010a&filter-autoc_textentry=Test%20Elis9010a&filter-completionstatus=9999&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010a&filter-autoc_textentry=Test%20Elis9010a&filter-summarycolumns:user_email=0&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010a&filter-autoc_textentry=Test%20Elis9010a&filter-summarycolumns:user_email=1&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010a&filter-autoc_textentry=Test%20Elis9010a&filter-summarycolumns:cur_name=0&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010a&filter-autoc_textentry=Test%20Elis9010a&filter-summarycolumns:cur_name=1&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010a&filter-autoc_textentry=Test%20Elis9010a&filter-summarycolumns:cur_timecompleted=0&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010a&filter-autoc_textentry=Test%20Elis9010a&filter-summarycolumns:cur_timecompleted=1&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010a&filter-autoc_textentry=Test%20Elis9010a&filter-summarycolumns:cur_certificate=0&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010a&filter-autoc_textentry=Test%20Elis9010a&filter-summarycolumns:cur_certificate=1&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010a&filter-autoc_textentry=Test%20Elis9010a&filter-detailcolumns:cur_name=0&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010a&filter-autoc_textentry=Test%20Elis9010a&filter-detailcolumns:cur_name=1&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010a&filter-autoc_textentry=Test%20Elis9010a&filter-detailcolumns:class_role=0&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010a&filter-autoc_textentry=Test%20Elis9010a&filter-detailcolumns:class_role=1&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010b&filter-autoc_textentry=Test%20Elis9010b&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010b&filter-autoc_textentry=Test%20Elis9010b&filter-uid_dropdown={local_elisprogram_uset}+1&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010b&filter-autoc_textentry=Test%20Elis9010b&filter-ccc-curriculum-name=&filter-uid_dropdown=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010b&filter-autoc_textentry=Test%20Elis9010b&filter-ccc-curriculum-name={local_elisprogram_pgm}+1&filter-uid_dropdown=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010b&filter-autoc_textentry=Test%20Elis9010b&filter-ccc-curriculum-name={local_elisprogram_pgm}+2&filter-uid_dropdown=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010b&filter-autoc_textentry=Test%20Elis9010b&filter-ccc-courseset-name=&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010b&filter-autoc_textentry=Test%20Elis9010b&filter-ccc-course-name=&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010b&filter-autoc_textentry=Test%20Elis9010b&filter-ccc-course-name={local_elisprogram_crs}+2&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010b&filter-autoc_textentry=Test%20Elis9010b&filter-ccc-course-name={local_elisprogram_crs}+3&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010b&filter-autoc_textentry=Test%20Elis9010b&filter-ccc-course-name={local_elisprogram_crs}+6&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010b&filter-autoc_textentry=Test%20Elis9010b&filter-ccc-course-name={local_elisprogram_crs}+7&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010b&filter-autoc_textentry=Test%20Elis9010b&filter-ccc-class-idnumber=&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010b&filter-autoc_textentry=Test%20Elis9010b&filter-ccc-class-idnumber={local_elisprogram_cls}+1&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010b&filter-autoc_textentry=Test%20Elis9010b&filter-ccc-class-idnumber={local_elisprogram_cls}+2&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010b&filter-autoc_textentry=Test%20Elis9010b&filter-ccc-class-idnumber={local_elisprogram_cls}+11&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010b&filter-autoc_textentry=Test%20Elis9010b&filter-ccc-class-idnumber={local_elisprogram_cls}+12&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010b&filter-autoc_textentry=Test%20Elis9010b&filter-completionstatus=&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010b&filter-autoc_textentry=Test%20Elis9010b&filter-completionstatus=0&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010b&filter-autoc_textentry=Test%20Elis9010b&filter-completionstatus=1&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010b&filter-autoc_textentry=Test%20Elis9010b&filter-completionstatus=2&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010b&filter-autoc_textentry=Test%20Elis9010b&filter-completionstatus=9999&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010b&filter-autoc_textentry=Test%20Elis9010b&filter-summarycolumns:user_email=0&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010b&filter-autoc_textentry=Test%20Elis9010b&filter-summarycolumns:user_email=1&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010b&filter-autoc_textentry=Test%20Elis9010b&filter-summarycolumns:cur_name=0&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010b&filter-autoc_textentry=Test%20Elis9010b&filter-summarycolumns:cur_name=1&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010b&filter-autoc_textentry=Test%20Elis9010b&filter-summarycolumns:cur_timecompleted=0&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010b&filter-autoc_textentry=Test%20Elis9010b&filter-summarycolumns:cur_timecompleted=1&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010b&filter-autoc_textentry=Test%20Elis9010b&filter-summarycolumns:cur_certificate=0&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010b&filter-autoc_textentry=Test%20Elis9010b&filter-summarycolumns:cur_certificate=1&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010b&filter-autoc_textentry=Test%20Elis9010b&filter-detailcolumns:cur_name=0&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010b&filter-autoc_textentry=Test%20Elis9010b&filter-detailcolumns:cur_name=1&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:class_role=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010b&filter-autoc_textentry=Test%20Elis9010b&filter-detailcolumns:class_role=0&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-autoc_id=Test%20Elis9010b&filter-autoc_textentry=Test%20Elis9010b&filter-detailcolumns:class_role=1&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0 |
          | /local/elisreports/render_report_page.php?report=user_class_completion&filter-uid_usingdropdown=1&filter-uid_dropdown=&filter-ccc-curriculum-name=&filter-autoc_id=&filter-autoc_textentry=&filter-ccc-courseset-name=&filter-ccc-course-name=&filter-ccc-class-idnumber=&filter-completionstatus=&filter-summarycolumns:user_email=0&filter-summarycolumns:cur_name=0&filter-summarycolumns:cur_timecompleted=0&filter-summarycolumns:cur_certificate=0&filter-detailcolumns:cur_name=0&filter-detailcolumns:class_role=0 |

# This file auto-generated - do not edit!
